### ISSUE TITLE
Error reading from server

### ISSUE THREAD

**Issue by cristobalcar** [OuhscBbmc/REDCapR#164]
Hi guys, I'm working with a REDCap server in which I'm getting this error.
I have no problem with other REDCap server...

`> data <- redcap_read(redcap_uri=uri, 
+                             token=token,
+                             fields='record_id'
+                             )$data
The data dictionary describing 91 fields was read from REDCap in 2.4 seconds.  The http status code was 200.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer`

Thank you!

**Comment by wibeasley** [comment]
@cristobalcar, I wondered if the yesterday's  [new version](https://cran.r-project.org/web/packages/curl/NEWS) of `curl` was involved, but all my tests pass.  Here are a few suggestions.
1. Update REDCapR from GitHub (with `devtools::install_github(repo="OuhscBbmc/REDCapR")`) and curl from CRAN.
1. See what happens when the `fields` parameter isn't set. (It could be misspelled)
1. try `redcap_read_oneshot()`
1. Follow the [troubleshooting](https://cdn.rawgit.com/OuhscBbmc/REDCapR/master/inst/doc/TroubleshootingApiCalls.html) guide.

If these things fail, give me more info, and I'll try to help.

**Comment by wibeasley** [comment]
@cristobalcar, I'm going to close the issue for now.  Feel free to reopen it (with the information requested above) when you'd like.

**Comment by wibeasley** [comment]
@cristobalcar, thanks for the shout-out during your REDCapCon presentation.  As I said above, feel free to reopen the issue if it's not worked out.  -Will
