### ISSUE TITLE
Writing to Metadata

### ISSUE THREAD

**Issue by Stephonomon** [OuhscBbmc/REDCapR#248]
Is there a way to write back to a project's metadata (data-dictionary)? Say I use the API to export a field with choices, and I want to use R to manipulate and then upload the choices back to the dictionary.

![image](https://user-images.githubusercontent.com/9829881/62825322-cc06a280-bb77-11e9-941d-6e9bd9827ada.png)

**Comment by wibeasley** [comment]
@Stephonomon, thanks for prompting this.  I haven't thought about adding a feature for this, because it would be difficult to add unit tests (at least the way I currently do it).

Have you looked at the internal function `REDCapR:::kernal_api()` and its [examples](https://ouhscbbmc.github.io/REDCapR/reference/kernel_api.html#examples)?

I haven't tested this, but it might be as straight-forward as

```r
config_options <- NULL
uri            <- "https://bbmc.ouhsc.edu/redcap/api/"
token          <- "zzzz"
post_body      <- list(
  token    = token,
  content  = 'metadata',
  data     = csv,        # Whatever you're trying to import.
  format   = 'csv'
)
kernel <- REDCapR:::kernel_api(uri, post_body, config_options)
```

For the `csv` variable, check out the internals of [`redcap-write-oneshot.R()`](https://github.com/OuhscBbmc/REDCapR/blob/master/R/redcap-write-oneshot.R).

**Comment by wibeasley** [comment]
@Stephonomon, any update on this?  Did the code above work?
