### ISSUE TITLE
User roles export

### ISSUE THREAD

**Issue by chillywings** [OuhscBbmc/REDCapR#261]
Hi, I'd like to know if it would be possible to export user role data. Ie. the names of the roles, who's in which role, and what rights that role has. I tried redcap_users_export(), which does tell me about the rights of individual users, but it does not tell me anything about roles. The simplest way to do this would be to add a column to the output of redcap_users_export() indicating what role a user is assigned to (preferably for both of the returned data frames). Thanks!

**Comment by wibeasley** [comment]
@chillywings, if I understand correctly, this is a feature request for the actual REDCap, instead of a feature request for REDCapR?

username,email,firstname,lastname,expiration,data_access_group,data_access_group_id,design,user_rights,data_access_groups,data_export,reports,stats_and_charts,manage_survey_participants,calendar,data_import_tool,data_comparison_tool,logging,file_repository,data_quality_create,data_quality_execute,api_export,api_import,mobile_app,mobile_app_download_data,record_create,record_rename,record_delete,lock_records_all_forms,lock_records,lock_records_customization,forms

**Comment by chillywings** [comment]
Hey @wibeasley, thanks for looking into this. My apologies I wasn't sure if that data was available from redcap or not. If not, then yes.. I'll see if I can add a feature request to redcap. I was asking here because of this line in the documentation for redcap_users_export():

> Note: If the user has been assigned to a user role, it will return the user with the role’s defined
privileges.

Thus I wasn't sure if the name of the user's role was being returned from redcap or not.

**Comment by wibeasley** [comment]
@chillywings, I see what you mean.  That's how I interpret that sentence too.  (BTW, the sentence is still in the 9.0.0 API documentation.)  

I modified one of the test projects so a test user belongs to a role.  Nothing changed.  (This project is called in the [`redcap_users_export()` example](https://ouhscbbmc.github.io/REDCapR/reference/redcap_users_export.html) if you want to try it yourself.)  I didn't see any new column pop up.  I also checked the API playground --upstream of REDCapR.  In the [REDCapR fx](https://github.com/OuhscBbmc/REDCapR/blob/master/R/redcap-users-export.R), I intentionally used `readr::cols()` (instead of `readr::cols_only()`) so that any new columns introduced in future REDCap versions would pass through to the user.  Maybe your version of REDCap has it?

I looked at the underlying MySQL tables.  The 4th column of the `redcap_user_rights` table is `role_id`, which I assume connects to the first column in the `redcap_user_roles` table, shown below.  I imagine they were planning to left join on `role_id` and return `ur.role_name` in the API method?  Or maybe I'm misinterpreting that sentence.

When you make the feature-request, please 
1. link to/from this issue so I can follow easier, and
2. propose that the `role_name` column appear --no matter what.  I really don't want to insert conditional logic that would test for the presence of that column.  Plus, even within the same project, some users could belong to roles, and some won't, so blank cells are inevitable.

```sql
SELECT
    ur.role_id,
    ur.project_id,
    ur.role_name,   -- Doesn't show up in 9.0.0 API
    ur.lock_record,
    ur.lock_record_multiform,
    ur.lock_record_customize,
    ur.data_export_tool,
    ur.data_import_tool,
    ur.data_comparison_tool,
    ur.data_logging,
    ur.file_repository,
    ur.double_data,
    ur.user_rights,
    ur.data_access_groups,
    ur.graphical,
    ur.reports,
    ur.design,
    ur.calendar,
    ur.data_entry,
    ur.api_export,
    ur.api_import,
    ur.mobile_app,
    ur.mobile_app_download_data,
    ur.record_create,
    ur.record_rename,
    ur.record_delete,
    ur.dts,
    ur.participants,
    ur.data_quality_design,
    ur.data_quality_execute,
    ur.data_quality_resolution,
    ur.random_setup,
    ur.random_dashboard,
    ur.random_perform,
    ur.realtime_webservice_mapping,
    ur.realtime_webservice_adjudicate,
    ur.external_module_config
FROM `rob_is_my_hero`.`redcap_user_roles` as ur
```

**Comment by chillywings** [comment]
My apologies about the delay here. I've submitted the feature request and included a link to this issue. However I didn't get any sort of link to track the issue on the Redcap end. Thanks for the help!
