### ISSUE TITLE
update troubleshooting document

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#278]
The [troubleshooting document](https://github.com/OuhscBbmc/REDCapR/blob/master/vignettes/TroubleshootingApiCalls.Rmd) hasn't changed much since @nutterb and I wrote it in 2014 (#23).  There are a few things that should be added/updated.
- [x] include the API playground
- [x] verify the metadata can be retrieved before trying the data itself (would have helped diagnose #269 & #272  a little faster)
- [x] switch from RCurl to httr for vanilla-R section
- [x] change from third-person to second-person.  (*e.g.*, "verify the user" to "verify")
- [x] add new "Common Language-Agnostic Gotchas" section
- [x] add new "General Troubleshooting Advice" section
- [x] include step for [`validate_for_write()`](https://ouhscbbmc.github.io/REDCapR/reference/validate.html)

@nutterb -I'm adding the metadata section for redcapAPI.  I'll tell you when I'm done with this checklist, and you're more than welcome to change anything.

@vortexing & @sybandrew, you've been through this recently (with #269 & #272).  Any suggestions how it could have helped your cases faster?

Everyone else -we'd like this document to stay useful to as many users & institutions as possible.  Feel free to propose anything that you think will help.

- [ ] Announce update in the forums and invite others to PR.

The latest master version is [available](https://ouhscbbmc.github.io/REDCapR/articles/TroubleshootingApiCalls.html).  The dev version might  lag by a few days.

**Comment by vortexing** [comment]
I think my issue was mainly that I didn't realize that the problem was in my data dictionary rather than an R problem or an API problem.  If the error message when the content was not able to be transformed into a data frame indicated that the problem was a data dictionary parsing problem, then I would say that the help text you have here to go look at my dictionary in something that isn't Excel would be perfect.  I wonder in the help text here: https://ouhscbbmc.github.io/REDCapR/articles/TroubleshootingApiCalls.html#gotchas-agnostic would be best to include possible error messages like I posted so people would be more likely to realize this was actually their problem?
