### ISSUE TITLE
`sanitize_token()` doesn't allow lowercase characters

### ISSUE THREAD

**Issue by jmbarbone** [OuhscBbmc/REDCapR#347]
Adding a small change in `sanitize_token()` with `toupper()` could save some work for people with API tokens stored with lowercase character data.

``` r
library(REDCapR)
sanitize_token("12345678901234567890123456ABCDEF")
#> [1] "12345678901234567890123456ABCDEF"
sanitize_token("12345678901234567890123456abcdef")
#> Error in sanitize_token("12345678901234567890123456abcdef"): The token is not a valid 32-character hexademical value.
packageVersion("REDCapR")
#> [1] '1.0.0'
```

<sup>Created on 2021-07-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by wibeasley** [comment]
Thanks @jmbarbone.  I restricted to uppercase intentionally, because REDCap's token generating code wasn't producing any lowercase letters.  I assume it generated lowercase letters for you?  I guess their code changed.

If so, do you mind removing the call to `toupper()`, and instead loosen the regex so it accommodates lowercase letters from a to z?  The pattern would then be defined like this (notice the extra "a-f")

```r
  pattern <- "^([0-9A-Fa-f]{32})(?:\\n)?$"
```

**Comment by jmbarbone** [comment]
Yes, @wibeasley, all the API tokens I've seen use lowercase characters.

The reason I used `toupper()` instead of adjusting the `regex` was to make sure that the outputs would be the same regardless of the original case of `token` in case there were other checks that demanded upper case tokens.  But from local testing it seems that adjusting just the `pattern` is safe.

**Comment by wibeasley** [comment]
I'm glad you figured it out and told me instead of turning off the validation.
