### ISSUE TITLE
Record names that do not comply to the REDCapR pattern

### ISSUE THREAD

**Issue by AlexBalhuizen** [OuhscBbmc/REDCapR#357]
Hi,
I tried to use REDCapR_write and REDCapR_write_oneshot to batch upload pdfs.
Each file has the record id as its filename. When I use the REDcap playground code or redcapAPI it works, but here it is only one file per time.
The record names are uniquely numbered as: ABC123-X01B-M01 as they are specific for sampling sites, occasions, and vial numbers.

When I run the code it uses ABC123, and if I do "" as "ABC123-X01B-M01", it returns an error.

REDCapR_write
_#Define some constants
uri    <- "https://redcapxxx/api/"
token  <- "TOKEN" # The simple project -pid 
field  <- "portion_files_fj"
event  <- "sorting_arm_1'" # only for longitudinal events
#Upload a single image file.
record    <- "ABC123-X01B-M01"
file_path <- system.file("C://FJpdfs//ABC123-X01B-M01.pdf", package="REDCapR")

It gives me the following error:

Error in REDCapR::redcap_upload_file(file_name = file_path, record = record, : Assertion on 'file_name' failed: Must comply to pattern '^.{1,}$'.

Is it possible to run batch uploading with these record names?
I

**Comment by wibeasley** [comment]
Thanks for explaining it, @AlexBalhuizen.  I'm not sure how `REDCapR::redcap_write()` is related to this, so for now I'll concentrate on the error message that the file names aren't complying.

I'm stumped because that is a very permissive regex.  It's requiring only that the string has at least one character.

https://github.com/OuhscBbmc/REDCapR/blob/44d4cc21bfe3b7c0224a413ce2e355ec38f69570/R/redcap-upload-file-oneshot.R#L102


In isolation, that file name passes.  Can you double check that is the error message associated with the ABC123... file?
```r
checkmate::assert_character("C://FJpdfs//ABC123-X01B-M01.pdf", any.missing=FALSE, len=1, pattern="^.{1,}$")
```

If that doesn't solve it, please make sure REDCapR is the latest version and run the documentation example for [`REDCapR::redcap_upload_file_oneshot()`](https://ouhscbbmc.github.io/REDCapR/reference/redcap_upload_file_oneshot.html).

If that passes, please provide more information about the error with your dataset, such as `traceback()`.

**Comment by AlexBalhuizen** [comment]
I tried a couple of versions of the record name. It seems there are two problems one is that I use a dash - in the record name. Due to this, I have to use single quotes or double quotes to have R use the full record name, but it seems then that redcapR doesn't work with either single quotes or double quotes to define the record name.

For example:
If I run a quoted "P" as record
record    <- "P"
Error in REDCapR::redcap_upload_file(file_name = file_path, record = record, : Assertion on 'file_name' failed: Must comply to pattern '^.{1,}$'.

While redcapr processes everything without quotes or dashes, e.g. with underscore instead of dash. Here, error not found as I did run it without a token.
> record    <- ABC0123
Error: object 'ABC0123' not found
> #Upload a single image file.
> record    <- ABC0123-X01B-M01
Error: object 'ABC0123' not found
> record    <- ABC0123_X01B_M01
Error: object 'ABC0123_X01B_M01' not found
> record    <- "ABC0123_X01B_M01"


If I run checkmate it returns empty.
