### ISSUE TITLE
better documentation for the url

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/REDCapR#395]
inspired by #394, the REDCapR package should throw a better error message when passed a bad URL to a REDCap server.  It probably goes in https://github.com/OuhscBbmc/REDCapR/blob/main/R/kernel-api.R.

Maybe I can better parse the [curl](https://cran.r-project.org/package=curl) or [httr](https://cran.r-project.org/package=httr) error message.  If that's not possible, maybe I include a separate call just to the server to check for a response.  Adding a round-trip server call isn't the optimal performance decision, but that's gotta be small and the tradeoff is worth the improved usability.

**Comment by sutzig** [comment]
Thank you @wibeasley. My experience was a misunderstanding of what was required for a complete/valid URI. I don't know if all API calls end with or include the string "api", but, if that's the case, perhaps this could be reflected in the documentation and a function to check that the value entered for the redcap_uri ends with or include "api". My error was using only "https://server.org/" rather than "https://server.org/apps/redcap/api/" I was able to identify my error by going to the API Playground section of the RedCap project, which may another resource to call out in the documentation.

**Comment by wibeasley** [comment]
1. Sure, I can do that with a regex like `^.+?/api/?$`, which wouldn't cost a round trip to the server
2. Maybe it could be a warning (not an error) in case someone is doing something unconventional redirecting paths.
3.  Is there anything you'd change/add to `redcap_read()`'s [documentation](https://ouhscbbmc.github.io/REDCapR/reference/redcap_read.html), and its [examples](https://ouhscbbmc.github.io/REDCapR/reference/redcap_read.html#examples) below?

**Comment by sutzig** [comment]
I guess I would more explicitly call out the expected URI syntax in the redcap_uri argument description (i.e. "The URI (uniform resource identifier) of the REDCap project API generally formatted as <https://server.org/apps/redcap/api/>. Required.") and/or create a more explicitly focused redcap_read example highlighting the expect URI syntax. The example didn't seem to apply to my issue when I first reviewed it since I wasn't trying to specify column types.

**Comment by wibeasley** [comment]
Ok, in that case I'll chicken out and not test the url.  But as you suggested, provide a better example of the url.

I updated the documentation of each function that uses the parameter.  I also added this entry to the [troubleshooting guide](https://ouhscbbmc.github.io/REDCapR/articles/TroubleshootingApiCalls.html).

--------------

1. **Is the URL/URI correct?**  Notice the url typically resembles https://bbmc.ouhsc.edu/redcap/api/> and *not* <https://bbmc.ouhsc.edu/> (even if <https://bbmc.ouhsc.edu/> redirects to <https://bbmc.ouhsc.edu/redcap>).
