### ISSUE TITLE
De-identified data?

### ISSUE THREAD

**Issue by haozhu233** [OuhscBbmc/REDCapR#74]
Hello, I just tried this REDCapR Package and it worked great! However, I'm wondering if it's possible to ask REDCap API to export de-identified data based on the user rights? 

Currently, if I switch my user-right to de-identified data, it will return an Error message saying "Error in nrow(ds) : object 'ds' not found".

**Comment by wibeasley** [comment]
I'm happy to hear it, @haozhu233.  What version of REDCap are you using?  Version 6+ of the server restricts PHI columns, based on the user's privileges.  And any security the REDCapR package might implement could be easily avoided by malicious users (since the package runs on the client and is under their control).  Am I understanding your question?  Please correct me if I'm not.

(This paragraph may be more detail that you'd like.)  On a related note, to read or write in the batch mode (which is the default), the user has to have full access to the PHI.  Otherwise the subject's record ID is hashed, and isn't available to use when subsets of rows are requested on subsequent read/write calls (which is handled automatically by those calls).

If the user doesn't have PHI privileges, the `redcap_read_oneshot()` and `redcap_write_oneshot()` need to be used instead.

**Comment by nutterb** [comment]
I was half way through a similar response.  Will beat me to it.

But he's correct on all counts.  If you want to control whether a person gets de-identified or identifiable data through the API, you have to do that through the User Rights page on the project.  There is no parameter you can give to the API to ask it to de-identify the data.

And if you're running an earlier version of REDCap (less than 6.0), then _any_ API call retrieves the full, identifiable data.  There's no control on it there.

**Comment by haozhu233** [comment]
@wibeasley @nutterb Thank you for your answers. I followed your direction and used `redcap_read_oneshot` and I got my de-identified data. Thank you so much for your help.

**Comment by wibeasley** [comment]
You're right, I need to expand the [existing error message](https://github.com/OuhscBbmc/REDCapR/blob/0007db12bb243f1c6b244a32810f10fd813eaf4a/R/redcap_read.R#L134-L139) to propose the 'oneshot' methods should be used if it's unwise to open up the user's privileges.  

Maybe a future version of the server will allow a client record to be retrieved with the hashed ID instead of the real ID.  ...or I'm open to other ideas if anyone has them.

By the way @haozhu233, was the [existing error message](https://github.com/OuhscBbmc/REDCapR/blob/0007db12bb243f1c6b244a32810f10fd813eaf4a/R/redcap_read.R#L134-L139) helpful at all?  Or did you arrive at the problem a different way?
```r
if( all(nchar(uniqueIDs)==32L) )
    warning("It appears that the REDCap record IDs have been hashed. ", 
            "For `redcap_read` to function properly, the user must have Export permissions for the 'Full Data Set'. ",
            "To grant the appropriate permissions: ",
            "(1) go to 'User Rights' in the REDCap project site, ",
            "(2) select the desired user, and then select 'Edit User Privileges', ",
            "(3) in the 'Data Exports' radio buttons, select 'Full Data Set'.")
```

(And thanks for the assist, @nutterb.  Hope things are fun at your new job.)

**Comment by haozhu233** [comment]
@wibeasley Somehow I wasn't able to get this error message as it reported error on the half way. 

Here is what I got when I had all data access

    > ds_all_rows_all_fields <- redcap_read(redcap_uri=uri, token=token)$data
    9 records and 484 columns were read from REDCap in 0.5 seconds.  The http status code was 200.
    Starting to read 4 records  at 2015-05-01 16:24:41
    Reading batch 1 of 1, with subjects 1 through 4 (ie, 4 unique subject records).
    9 records and 484 columns were read from REDCap in 0.4 seconds.  The http status code was 200.

This is what I got after I changed my user rights to see "de-identified data" only. 

    > ds_all_rows_all_fields <- redcap_read(redcap_uri=uri, token=token)$data
    9 records and 414 columns were read from REDCap in 0.6 seconds.  The http status code was 200.
    Starting to read 4 records  at 2015-05-01 16:08:12
    Reading batch 1 of 1, with subjects 4561e7b79e2849121cf8ddeda1b2334d through da49cd4726823a8dd3b4630fd7d4d75f (ie, 4 unique subject records).
    Error in nrow(ds) : object 'ds' not found

I checked your codes but I didn't see a variable called `ds`. I'm a little confused here.

**Comment by haozhu233** [comment]
@wibeasley I updated my `REDCapR` to the github version and I actually get a different error message this time. 

    > ds_all_rows_all_fields <- redcap_read(redcap_uri=uri, token=token)
    The data dictionary describing 0 fields was read from REDCap in 0.3 seconds.  The http status code was 200.
    Error in if (nchar(fields_collapsed) == 0) fields_collapsed <- ifelse(is.null(fields),  : 
     argument is of length zero
    In addition: Warning message:
    In REDCapR::redcap_metadata_read(redcap_uri = redcap_uri, token = token,  :
      The `REDCapR::redcap_metadata_read()` function is very new and under development; it's likely to change in the future, especially how it handles checkboxes.

**Comment by wibeasley** [comment]
Thanks @haozhu233.  One last question for now.  What version of REDCapR are you using?  In the GitHub versions since Feb 8, I thought I removed the possibility of that error message with [this `if/else` block](https://github.com/OuhscBbmc/REDCapR/blob/0007db12bb243f1c6b244a32810f10fd813eaf4a/R/redcap_read_oneshot.R#L191-L200), but maybe I'm overlooking something.

*Don't feel obligated to do this*, but I'm curious if you'll still see this error message with a recent version (that you can get by running the following code).
```r
install.packages("devtools")
devtools::install_github(repo="OuhscBbmc/REDCapR")
```

This is one of those scenarios where I feel like a helpful error message could make or break the frustration of the caller.

**Comment by haozhu233** [comment]
@wibeasley Hi, Will, the institute I'm working at is using REDCap 6.2.4, which I think is not the most recent version. 

Also, in fact, I tried the github version before but it produced some more error messages even if I have full access to the database. As far as I can tell, it seems that it could not read the correct information from the data dictionary. I tried it on both R 3.1.3 and R 3.2.0 and I got the same error message so I guess it's not due to the recent R update. 

    > a<-redcap_read(redcap_uri=url, token=key)
    The data dictionary describing 0 fields was read from REDCap in 0.6 seconds.  The http status code was 200.
    Error in if (nchar(fields_collapsed) == 0) fields_collapsed <- ifelse(is.null(fields),  : 
      argument is of length zero
    In addition: Warning message:
    In REDCapR::redcap_metadata_read(redcap_uri = redcap_uri, token = token,  :
      The `REDCapR::redcap_metadata_read()` function is very new and under development; it's likely to change in the future, especially how it handles checkboxes.

I'm willing to make some contributions and I will look into this issue a little bit more over the weekend.

**Comment by wibeasley** [comment]
I'm sorry, I meant to ask about the the REDCap**R** package version.  (Not the version of R or the REDCap server.)

Again, don't feel obligated.

**Comment by haozhu233** [comment]
Here is my session information and you can see I'm currently using REDCapR_0.8-15. I'm currently using my home computer, on which I haven't updated the R, so it's still 3.1.3. I also want to confirm that even after I updated all my installed package from CRAN, the problem for the github version of REDCapR is still there. 

    > sessionInfo()
    R version 3.1.3 (2015-03-09)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 8 x64 (build 9200)
    
    locale:
    [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] REDCapR_0.8-15
    
    loaded via a namespace (and not attached):
    [1] bitops_1.0-6   httr_0.6.1     RCurl_1.95-4.6 stringr_0.6.2  tools_3.1.3

**Comment by wibeasley** [comment]
That's very helpful @haozhu233.  I'll dig into it to see what scenarios I neglected.
