### ISSUE TITLE
Failure with dev version of testthat

### ISSUE THREAD

**Issue by hadley** [OuhscBbmc/REDCapR#76]
```
checking tests ... ERROR
Running the tests in ‘tests/test-all.R’ failed.
Last 13 lines of output:
  8. Failure (@test-read_batch.R#202): All Records -Raw and DAG 
  9. Error: Smoke Test 
  1. Error: Write Batch -Insert 
  2. Error: Write Batch -Update One Field 
  3. Error: Write Batch -Update Two Fields 
  4. Error: Smoke Test 
  5. Error: Write One Shot -Insert 
  6. Error: Write One Shot -Update One Field 
  7. Error: Write One Shot -Update Two Fields 
  8. ...
  
  Error: testthat unit tests failed
  Execution halted
```

Could you please take a look?

**Comment by wibeasley** [comment]
I don't see a problem.  Is this what you wanted me to check?  I've run it three times (once with my dev branch) with the GitHub and CRAN versions of `httr`.  Is there something else I should run?

I'm betting the problems you saw are related to the finicky test server I'm using.  Recently Vandy gave me privileges to use their test server, and I hope to switch over in a week or two.

Another possibilities is that only one test suite can be run at a time.  If two run at once, they can step on each other's toes during the *write* tests.  REDCap doesn't have an API function to allow me to create projects/databases (since that's not really necessary in clinical research), so the "write-test databases" are reused over and over (and their data is erased between runs).

I see that error message you pasted primarily involved the write tests.  Any chance two were run in parallel?

```
> devtools::install("hadley/testthat")
{...then I built it with RStudio...}
> test_results_checked <- devtools::test()
Testing REDCapR
Create Batch Glossary : .........
FileOneshot : ...............................................................
Metadata Read : .........................................
Metadata Utilities : ..
Project Object : ................
Read Batch - Longitudinal : ....................
Read Batch - Simple : ...................................................................
Read Oneshot : .........................................
Russian : ..
Replace NAs : .........
Validate data frame for writing to REDCap : ........
Write Batch : ..........................................
Write Oneshot : ..........................................
```

**Comment by hadley** [comment]
You really need to run `R CMD check`. If you don't see any problems, it's probably just something local to me.  (It might be that you expect all the suggested packages to be installed, which I don't do when checking so many packages)

**Comment by wibeasley** [comment]
Regarding the suggested packages, `RODBC` functions aren't involved in testing.  And there's a  chance [the others](https://github.com/OuhscBbmc/REDCapR/blob/master/DESCRIPTION#L36-L42) were loaded on your machine already.
```
Suggests:
    devtools,
    knitr,
    methods,
    RODBC,
    testit,
    testthat (>= 0.9)
```

I'm getting a weird error when the roxygenized tags are converted to Rd files, so I can't check the package right now.  I'll look into it more tonight after I meet some of today's deadlines.

There's some weird text wrapping occurring when the Rd files are written.  The parameters don't start their own line.  This results in errors like `Warning: bad markup (extra space?) at REDCapR.Rd:11:61`.  This occurs even after the CRAN versions (of devtools, roxygen2, and testthat) are installed and I execute `git checkout -- .`.

The old Rd was
```
  before it's split.}

  \item{batch_size}{The maximum number of subject records a
  single batch should contain.}
``` 
and it's now
```
  before it's split.} \item{batch_size}{The maximum number
  of subject records a single batch should contain.}
```

Since it's not affecting any of your other packages being built and checked, I'm guessing the problem's local to my computer, and related to line endings or something.  I'll try to isolate the problem tonight.

**Comment by haozhu233** [comment]
@wibeasley I have a feeling that this is actually what I experienced last week. I just quickly checked your past commits and I found that I started to get error message since "Use metadata to make batching more efficient" (ID: [39a4a23](https://github.com/OuhscBbmc/REDCapR/commit/39a4a23d1cb921e5bd459294152d63e198252ad4) ). I hope it's helpful for you to debug.

**Comment by wibeasley** [comment]
Thanks @haozhu233.  Did you really checkout previous commits to see when is started popping up?  If so, I really appreciate the extra effort.  (If not, I still appreciate the time you spent informing me in #74).

I'll keep trying to find how that non-existent fields variable squeaks by the `if`s.  But I'm going to wait to tackle that until some platform issues on Travis are resolved (ie, https://github.com/OuhscBbmc/REDCapR/issues/78)

By the way, the problem I described immediately above was solved with [removing the roxygen2 line wrapping](https://github.com/OuhscBbmc/REDCapR/commit/c712198081ea90c13c2f5b7f0256fa8bec539717#diff-35ba4a2677442e210c23a00a5601aba3L46) which had been there for months.

**Comment by wibeasley** [comment]
@hadley, I'm pretty sure whatever came up on your machine had nothing to do with the dev version of testthat, and I'm closing the issue.

FWIW, running tests through the preview version of RStudio (0.99.435) and master branch of testthat doesn't display the progress dots in the 'Build' pane anymore.  It happens on both a Ubuntu 14.04 and Windows 8 OS.  The progress dots reappear when I fall back to the CRAN version.  Also when `devtools::test()` is run.

Tell me if you want me to open a dedicated testthat issue and/or investigate more.

```r
==> Sourcing R files in 'tests' directory

testthat results ================================================================
OK: 372 SKIPPED: 0 FAILED: 0

Tests complete
```
